#!/usr/bin/env python3
"""Extract a lightweight salivary-study GLB from the registered BodyParts3D organ layer.

This does not alter registration: selected meshes retain their transforms from the
existing head-organs.glb generated by the BodyParts3D v4.3 build pipeline.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import trimesh

SOURCE = Path('assets/bodyparts3d/head-organs.glb')
OUTPUT = Path('assets/bodyparts3d/head-salivary.glb')
MANIFEST = Path('assets/bodyparts3d/salivary-manifest.json')
TARGET_FJ = {
    'FJ2761',  # Tongue
    'FJ2765',  # Left sublingual gland
    'FJ4643',  # Left sublingual gland alternate component
    'FJ2766',  # Left submandibular gland
    'FJ2767',  # Right sublingual gland
    'FJ2768',  # Right submandibular gland
}


def main() -> int:
    if not SOURCE.exists():
        raise SystemExit(f'Missing source asset: {SOURCE}')

    source = trimesh.load(SOURCE, force='scene', process=False)
    if not isinstance(source, trimesh.Scene):
        source = trimesh.Scene(source)

    out = trimesh.Scene()
    selected = []

    for node_name in source.graph.nodes_geometry:
        transform, geom_name = source.graph[node_name]
        text = f'{node_name} {geom_name}'
        fj = next((value for value in TARGET_FJ if value in text), None)
        if not fj:
            continue
        geometry = source.geometry[geom_name].copy()
        out.add_geometry(
            geometry,
            node_name=node_name,
            geom_name=geom_name,
            transform=np.asarray(transform),
        )
        selected.append({
            'fj_id': fj,
            'node': node_name,
            'geometry': geom_name,
            'faces': int(len(geometry.faces)),
        })

    unique_fj = sorted({item['fj_id'] for item in selected})
    required = {'FJ2765', 'FJ2766', 'FJ2767', 'FJ2768'}
    missing = sorted(required - set(unique_fj))
    if missing:
        raise SystemExit(f'Missing required salivary meshes: {missing}; found {unique_fj}')

    OUTPUT.write_bytes(trimesh.exchange.gltf.export_glb(out, include_normals=True))
    MANIFEST.write_text(json.dumps({
        'source': str(SOURCE),
        'output': str(OUTPUT),
        'coordinateSystem': 'Unchanged from BodyParts3D Anatomy3D web export',
        'selectedFJ': unique_fj,
        'structures': selected,
        'bytes': OUTPUT.stat().st_size,
        'note': 'Includes the four available submandibular/sublingual gland meshes plus tongue context when available. No synthetic parotid or duct geometry.',
    }, indent=2, sort_keys=True))
    print(f'Built {OUTPUT} with {len(unique_fj)} FJ components, {OUTPUT.stat().st_size / 1024:.1f} KiB')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
